/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Rupiah = IDL.Nat;
export const Id = IDL.Nat;
export const AccountType = IDL.Variant({
  'bank' : IDL.Null,
  'cash' : IDL.Null,
});
export const LedgerEntryDTO = IDL.Record({
  'entryType' : IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null }),
  'date' : Timestamp,
  'description' : IDL.Text,
  'accountType' : AccountType,
  'amount' : Rupiah,
});
export const AccountBalances = IDL.Record({
  'cashBalance' : Rupiah,
  'bankBalance' : Rupiah,
});
export const ExpenseCategory = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'isDefault' : IDL.Bool,
});
export const ExpenseEntry = IDL.Record({
  'id' : Id,
  'categoryId' : Id,
  'date' : Timestamp,
  'tagIds' : IDL.Vec(Id),
  'accountType' : AccountType,
  'notes' : IDL.Text,
  'amount' : Rupiah,
});
export const LedgerEntry = IDL.Record({
  'id' : Id,
  'entryType' : IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null }),
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'accountType' : AccountType,
  'amount' : Rupiah,
});
export const ProfitEntry = IDL.Record({
  'id' : Id,
  'date' : Timestamp,
  'notes' : IDL.Text,
  'amount' : Rupiah,
});
export const SaleEntry = IDL.Record({
  'id' : Id,
  'date' : Timestamp,
  'onlineAmount' : Rupiah,
  'notes' : IDL.Text,
  'cashAmount' : Rupiah,
});
export const Tag = IDL.Record({ 'id' : Id, 'name' : IDL.Text });
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'businessName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExpense' : IDL.Func(
      [Timestamp, Rupiah, Id, AccountType, IDL.Vec(Id), IDL.Text],
      [Id],
      [],
    ),
  'createExpenseCategory' : IDL.Func([IDL.Text], [Id], []),
  'createLedgerEntry' : IDL.Func([LedgerEntryDTO], [Id], []),
  'createProfitEntry' : IDL.Func([Timestamp, Rupiah, IDL.Text], [Id], []),
  'createSale' : IDL.Func([Timestamp, Rupiah, Rupiah, IDL.Text], [Id], []),
  'createTag' : IDL.Func([IDL.Text], [Id], []),
  'deleteExpense' : IDL.Func([Id], [], []),
  'deleteProfitEntry' : IDL.Func([Id], [], []),
  'deleteSale' : IDL.Func([Id], [], []),
  'getAccountBalances' : IDL.Func([], [AccountBalances], ['query']),
  'getAllExpenseCategories' : IDL.Func(
      [],
      [IDL.Vec(ExpenseCategory)],
      ['query'],
    ),
  'getAllExpenseCategoriesWithExpenses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ExpenseCategory, IDL.Vec(ExpenseEntry)))],
      ['query'],
    ),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
  'getAllLedgerEntries' : IDL.Func([], [IDL.Vec(LedgerEntry)], ['query']),
  'getAllProfits' : IDL.Func([], [IDL.Vec(ProfitEntry)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(SaleEntry)], ['query']),
  'getAllTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpense' : IDL.Func([Id], [IDL.Opt(ExpenseEntry)], ['query']),
  'getExpenseCategory' : IDL.Func([Id], [IDL.Opt(ExpenseCategory)], ['query']),
  'getLedgerEntry' : IDL.Func([Id], [IDL.Opt(LedgerEntry)], ['query']),
  'getProfitEntry' : IDL.Func([Id], [IDL.Opt(ProfitEntry)], ['query']),
  'getSale' : IDL.Func([Id], [IDL.Opt(SaleEntry)], ['query']),
  'getTag' : IDL.Func([Id], [IDL.Opt(Tag)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Rupiah = IDL.Nat;
  const Id = IDL.Nat;
  const AccountType = IDL.Variant({ 'bank' : IDL.Null, 'cash' : IDL.Null });
  const LedgerEntryDTO = IDL.Record({
    'entryType' : IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null }),
    'date' : Timestamp,
    'description' : IDL.Text,
    'accountType' : AccountType,
    'amount' : Rupiah,
  });
  const AccountBalances = IDL.Record({
    'cashBalance' : Rupiah,
    'bankBalance' : Rupiah,
  });
  const ExpenseCategory = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'isDefault' : IDL.Bool,
  });
  const ExpenseEntry = IDL.Record({
    'id' : Id,
    'categoryId' : Id,
    'date' : Timestamp,
    'tagIds' : IDL.Vec(Id),
    'accountType' : AccountType,
    'notes' : IDL.Text,
    'amount' : Rupiah,
  });
  const LedgerEntry = IDL.Record({
    'id' : Id,
    'entryType' : IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null }),
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'accountType' : AccountType,
    'amount' : Rupiah,
  });
  const ProfitEntry = IDL.Record({
    'id' : Id,
    'date' : Timestamp,
    'notes' : IDL.Text,
    'amount' : Rupiah,
  });
  const SaleEntry = IDL.Record({
    'id' : Id,
    'date' : Timestamp,
    'onlineAmount' : Rupiah,
    'notes' : IDL.Text,
    'cashAmount' : Rupiah,
  });
  const Tag = IDL.Record({ 'id' : Id, 'name' : IDL.Text });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'businessName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExpense' : IDL.Func(
        [Timestamp, Rupiah, Id, AccountType, IDL.Vec(Id), IDL.Text],
        [Id],
        [],
      ),
    'createExpenseCategory' : IDL.Func([IDL.Text], [Id], []),
    'createLedgerEntry' : IDL.Func([LedgerEntryDTO], [Id], []),
    'createProfitEntry' : IDL.Func([Timestamp, Rupiah, IDL.Text], [Id], []),
    'createSale' : IDL.Func([Timestamp, Rupiah, Rupiah, IDL.Text], [Id], []),
    'createTag' : IDL.Func([IDL.Text], [Id], []),
    'deleteExpense' : IDL.Func([Id], [], []),
    'deleteProfitEntry' : IDL.Func([Id], [], []),
    'deleteSale' : IDL.Func([Id], [], []),
    'getAccountBalances' : IDL.Func([], [AccountBalances], ['query']),
    'getAllExpenseCategories' : IDL.Func(
        [],
        [IDL.Vec(ExpenseCategory)],
        ['query'],
      ),
    'getAllExpenseCategoriesWithExpenses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ExpenseCategory, IDL.Vec(ExpenseEntry)))],
        ['query'],
      ),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
    'getAllLedgerEntries' : IDL.Func([], [IDL.Vec(LedgerEntry)], ['query']),
    'getAllProfits' : IDL.Func([], [IDL.Vec(ProfitEntry)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(SaleEntry)], ['query']),
    'getAllTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpense' : IDL.Func([Id], [IDL.Opt(ExpenseEntry)], ['query']),
    'getExpenseCategory' : IDL.Func(
        [Id],
        [IDL.Opt(ExpenseCategory)],
        ['query'],
      ),
    'getLedgerEntry' : IDL.Func([Id], [IDL.Opt(LedgerEntry)], ['query']),
    'getProfitEntry' : IDL.Func([Id], [IDL.Opt(ProfitEntry)], ['query']),
    'getSale' : IDL.Func([Id], [IDL.Opt(SaleEntry)], ['query']),
    'getTag' : IDL.Func([Id], [IDL.Opt(Tag)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };