/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountBalances {
  'cashBalance' : Rupiah,
  'bankBalance' : Rupiah,
}
export type AccountType = { 'bank' : null } |
  { 'cash' : null };
export interface ExpenseCategory {
  'id' : Id,
  'name' : string,
  'isDefault' : boolean,
}
export interface ExpenseEntry {
  'id' : Id,
  'categoryId' : Id,
  'date' : Timestamp,
  'tagIds' : Array<Id>,
  'accountType' : AccountType,
  'notes' : string,
  'amount' : Rupiah,
}
export type Id = bigint;
export interface LedgerEntry {
  'id' : Id,
  'entryType' : { 'credit' : null } |
    { 'debit' : null },
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'description' : string,
  'accountType' : AccountType,
  'amount' : Rupiah,
}
export interface LedgerEntryDTO {
  'entryType' : { 'credit' : null } |
    { 'debit' : null },
  'date' : Timestamp,
  'description' : string,
  'accountType' : AccountType,
  'amount' : Rupiah,
}
export interface ProfitEntry {
  'id' : Id,
  'date' : Timestamp,
  'notes' : string,
  'amount' : Rupiah,
}
export type Rupiah = bigint;
export interface SaleEntry {
  'id' : Id,
  'date' : Timestamp,
  'onlineAmount' : Rupiah,
  'notes' : string,
  'cashAmount' : Rupiah,
}
export interface Tag { 'id' : Id, 'name' : string }
export type Timestamp = bigint;
export interface UserProfile { 'name' : string, 'businessName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createExpense' : ActorMethod<
    [Timestamp, Rupiah, Id, AccountType, Array<Id>, string],
    Id
  >,
  'createExpenseCategory' : ActorMethod<[string], Id>,
  'createLedgerEntry' : ActorMethod<[LedgerEntryDTO], Id>,
  'createProfitEntry' : ActorMethod<[Timestamp, Rupiah, string], Id>,
  'createSale' : ActorMethod<[Timestamp, Rupiah, Rupiah, string], Id>,
  'createTag' : ActorMethod<[string], Id>,
  'deleteExpense' : ActorMethod<[Id], undefined>,
  'deleteProfitEntry' : ActorMethod<[Id], undefined>,
  'deleteSale' : ActorMethod<[Id], undefined>,
  'getAccountBalances' : ActorMethod<[], AccountBalances>,
  'getAllExpenseCategories' : ActorMethod<[], Array<ExpenseCategory>>,
  'getAllExpenseCategoriesWithExpenses' : ActorMethod<
    [],
    Array<[ExpenseCategory, Array<ExpenseEntry>]>
  >,
  'getAllExpenses' : ActorMethod<[], Array<ExpenseEntry>>,
  'getAllLedgerEntries' : ActorMethod<[], Array<LedgerEntry>>,
  'getAllProfits' : ActorMethod<[], Array<ProfitEntry>>,
  'getAllSales' : ActorMethod<[], Array<SaleEntry>>,
  'getAllTags' : ActorMethod<[], Array<Tag>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpense' : ActorMethod<[Id], [] | [ExpenseEntry]>,
  'getExpenseCategory' : ActorMethod<[Id], [] | [ExpenseCategory]>,
  'getLedgerEntry' : ActorMethod<[Id], [] | [LedgerEntry]>,
  'getProfitEntry' : ActorMethod<[Id], [] | [ProfitEntry]>,
  'getSale' : ActorMethod<[Id], [] | [SaleEntry]>,
  'getTag' : ActorMethod<[Id], [] | [Tag]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];