/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ExpenseCategory {
    id: Id;
    name: string;
    isDefault: boolean;
}
export interface LedgerEntryDTO {
    entryType: Variant_credit_debit;
    date: Timestamp;
    description: string;
    accountType: AccountType;
    amount: Rupiah;
}
export type Rupiah = bigint;
export interface LedgerEntry {
    id: Id;
    entryType: Variant_credit_debit;
    date: Timestamp;
    createdAt: Timestamp;
    createdBy: Principal;
    description: string;
    accountType: AccountType;
    amount: Rupiah;
}
export interface ProfitEntry {
    id: Id;
    date: Timestamp;
    notes: string;
    amount: Rupiah;
}
export interface Tag {
    id: Id;
    name: string;
}
export interface AccountBalances {
    cashBalance: Rupiah;
    bankBalance: Rupiah;
}
export type Id = bigint;
export interface SaleEntry {
    id: Id;
    date: Timestamp;
    onlineAmount: Rupiah;
    notes: string;
    cashAmount: Rupiah;
}
export interface ExpenseEntry {
    id: Id;
    categoryId: Id;
    date: Timestamp;
    tagIds: Array<Id>;
    accountType: AccountType;
    notes: string;
    amount: Rupiah;
}
export interface UserProfile {
    name: string;
    businessName: string;
}
export enum AccountType {
    bank = "bank",
    cash = "cash"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_credit_debit {
    credit = "credit",
    debit = "debit"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createExpense(date: Timestamp, amount: Rupiah, categoryId: Id, accountType: AccountType, tagIds: Array<Id>, notes: string): Promise<Id>;
    createExpenseCategory(name: string): Promise<Id>;
    createLedgerEntry(dto: LedgerEntryDTO): Promise<Id>;
    createProfitEntry(date: Timestamp, amount: Rupiah, notes: string): Promise<Id>;
    createSale(date: Timestamp, cashAmount: Rupiah, onlineAmount: Rupiah, notes: string): Promise<Id>;
    createTag(name: string): Promise<Id>;
    deleteExpense(expenseId: Id): Promise<void>;
    deleteProfitEntry(profitId: Id): Promise<void>;
    deleteSale(saleId: Id): Promise<void>;
    getAccountBalances(): Promise<AccountBalances>;
    getAllExpenseCategories(): Promise<Array<ExpenseCategory>>;
    getAllExpenseCategoriesWithExpenses(): Promise<Array<[ExpenseCategory, Array<ExpenseEntry>]>>;
    getAllExpenses(): Promise<Array<ExpenseEntry>>;
    getAllLedgerEntries(): Promise<Array<LedgerEntry>>;
    getAllProfits(): Promise<Array<ProfitEntry>>;
    getAllSales(): Promise<Array<SaleEntry>>;
    getAllTags(): Promise<Array<Tag>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExpense(expenseId: Id): Promise<ExpenseEntry | null>;
    getExpenseCategory(categoryId: Id): Promise<ExpenseCategory | null>;
    getLedgerEntry(ledgerId: Id): Promise<LedgerEntry | null>;
    getProfitEntry(profitId: Id): Promise<ProfitEntry | null>;
    getSale(saleId: Id): Promise<SaleEntry | null>;
    getTag(tagId: Id): Promise<Tag | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { AccountType as _AccountType, ExpenseCategory as _ExpenseCategory, ExpenseEntry as _ExpenseEntry, Id as _Id, LedgerEntry as _LedgerEntry, LedgerEntryDTO as _LedgerEntryDTO, ProfitEntry as _ProfitEntry, Rupiah as _Rupiah, SaleEntry as _SaleEntry, Tag as _Tag, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createExpense(arg0: Timestamp, arg1: Rupiah, arg2: Id, arg3: AccountType, arg4: Array<Id>, arg5: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(arg0, arg1, arg2, to_candid_AccountType_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(arg0, arg1, arg2, to_candid_AccountType_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async createExpenseCategory(arg0: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpenseCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpenseCategory(arg0);
            return result;
        }
    }
    async createLedgerEntry(arg0: LedgerEntryDTO): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createLedgerEntry(to_candid_LedgerEntryDTO_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLedgerEntry(to_candid_LedgerEntryDTO_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProfitEntry(arg0: Timestamp, arg1: Rupiah, arg2: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfitEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfitEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async createSale(arg0: Timestamp, arg1: Rupiah, arg2: Rupiah, arg3: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createSale(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSale(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTag(arg0: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTag(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteProfitEntry(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProfitEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProfitEntry(arg0);
            return result;
        }
    }
    async deleteSale(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSale(arg0);
            return result;
        }
    }
    async getAccountBalances(): Promise<AccountBalances> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountBalances();
            return result;
        }
    }
    async getAllExpenseCategories(): Promise<Array<ExpenseCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenseCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenseCategories();
            return result;
        }
    }
    async getAllExpenseCategoriesWithExpenses(): Promise<Array<[ExpenseCategory, Array<ExpenseEntry>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenseCategoriesWithExpenses();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenseCategoriesWithExpenses();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExpenses(): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLedgerEntries(): Promise<Array<LedgerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLedgerEntries();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLedgerEntries();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfits(): Promise<Array<ProfitEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfits();
            return result;
        }
    }
    async getAllSales(): Promise<Array<SaleEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSales();
            return result;
        }
    }
    async getAllTags(): Promise<Array<Tag>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTags();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpense(arg0: Id): Promise<ExpenseEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenseCategory(arg0: Id): Promise<ExpenseCategory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseCategory(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseCategory(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLedgerEntry(arg0: Id): Promise<LedgerEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLedgerEntry(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLedgerEntry(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfitEntry(arg0: Id): Promise<ProfitEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitEntry(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitEntry(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSale(arg0: Id): Promise<SaleEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSale(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSale(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTag(arg0: Id): Promise<Tag | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTag(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTag(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_AccountType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseEntry_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseEntry): ExpenseEntry {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_LedgerEntry_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LedgerEntry): LedgerEntry {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExpenseEntry]): ExpenseEntry | null {
    return value.length === 0 ? null : from_candid_ExpenseEntry_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExpenseCategory]): ExpenseCategory | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LedgerEntry]): LedgerEntry | null {
    return value.length === 0 ? null : from_candid_LedgerEntry_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfitEntry]): ProfitEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SaleEntry]): SaleEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tag]): Tag | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    categoryId: _Id;
    date: _Timestamp;
    tagIds: Array<_Id>;
    accountType: _AccountType;
    notes: string;
    amount: _Rupiah;
}): {
    id: Id;
    categoryId: Id;
    date: Timestamp;
    tagIds: Array<Id>;
    accountType: AccountType;
    notes: string;
    amount: Rupiah;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        date: value.date,
        tagIds: value.tagIds,
        accountType: from_candid_AccountType_n13(_uploadFile, _downloadFile, value.accountType),
        notes: value.notes,
        amount: value.amount
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    entryType: {
        credit: null;
    } | {
        debit: null;
    };
    date: _Timestamp;
    createdAt: _Timestamp;
    createdBy: Principal;
    description: string;
    accountType: _AccountType;
    amount: _Rupiah;
}): {
    id: Id;
    entryType: Variant_credit_debit;
    date: Timestamp;
    createdAt: Timestamp;
    createdBy: Principal;
    description: string;
    accountType: AccountType;
    amount: Rupiah;
} {
    return {
        id: value.id,
        entryType: from_candid_variant_n18(_uploadFile, _downloadFile, value.entryType),
        date: value.date,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        accountType: from_candid_AccountType_n13(_uploadFile, _downloadFile, value.accountType),
        amount: value.amount
    };
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ExpenseCategory, Array<_ExpenseEntry>]): [ExpenseCategory, Array<ExpenseEntry>] {
    return [
        value[0],
        from_candid_vec_n10(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bank: null;
} | {
    cash: null;
}): AccountType {
    return "bank" in value ? AccountType.bank : "cash" in value ? AccountType.cash : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): Variant_credit_debit {
    return "credit" in value ? Variant_credit_debit.credit : "debit" in value ? Variant_credit_debit.debit : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExpenseEntry>): Array<ExpenseEntry> {
    return value.map((x)=>from_candid_ExpenseEntry_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LedgerEntry>): Array<LedgerEntry> {
    return value.map((x)=>from_candid_LedgerEntry_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ExpenseCategory, Array<_ExpenseEntry>]>): Array<[ExpenseCategory, Array<ExpenseEntry>]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LedgerEntryDTO_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LedgerEntryDTO): _LedgerEntryDTO {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryType: Variant_credit_debit;
    date: Timestamp;
    description: string;
    accountType: AccountType;
    amount: Rupiah;
}): {
    entryType: {
        credit: null;
    } | {
        debit: null;
    };
    date: _Timestamp;
    description: string;
    accountType: _AccountType;
    amount: _Rupiah;
} {
    return {
        entryType: to_candid_variant_n7(_uploadFile, _downloadFile, value.entryType),
        date: value.date,
        description: value.description,
        accountType: to_candid_AccountType_n3(_uploadFile, _downloadFile, value.accountType),
        amount: value.amount
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    bank: null;
} | {
    cash: null;
} {
    return value == AccountType.bank ? {
        bank: null
    } : value == AccountType.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_credit_debit): {
    credit: null;
} | {
    debit: null;
} {
    return value == Variant_credit_debit.credit ? {
        credit: null
    } : value == Variant_credit_debit.debit ? {
        debit: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
